$bstack_sign_in_link = "//a[@id='Sign In']"
$bstack_sign_in_username_dropdown = "//div[@id='username']"
$bstack_sign_in_password_dropdown = "//div[@id='password']"
$bstack_sign_in_password_dropdown_option = "//div[text()='?']"
$bstack_sign_in_log_in_button = "//button[@id='login-btn']"
$bstack_sign_in_error = "//h3[@class='api-error']"
$bstack_logout_link = "//a[@id='logout']"
$bstack_product_add_to_cart_link = "//div[contains(@data-sku,'?')]/div[text()='Add to cart']"
$bstack_cart_model_opened = "//div[contains(@class,'float-cart--open')]"
$bstack_checkout_bag_quanity = "//span[@class='bag__quantity']"
$bstack_checkout_cart_close_button = "//div[contains(@class,'close-btn')]"
$bstack_checkout_cart_decrease_quantity_button = "//button[@class='change-product-button'][text()='-']"